apiVersion: v1
kind: Service
metadata:
  name: frappe-frontend
spec:
  selector:
    app: frappe-frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-frontend
  template:
    metadata:
      labels:
        app: frappe-frontend
    spec:
      containers:
        - name: frontend
          image: frappe/erpnext:v16.17.0
          command: ["nginx-entrypoint.sh"]
          env:
            - name: BACKEND
              value: frappe-backend:8000
            - name: FRAPPE_SITE_NAME_HEADER
              valueFrom:
                configMapKeyRef:
                  name: frappe-config
                  key: SITE_NAME
            - name: SOCKETIO
              value: frappe-websocket:9000
            - name: UPSTREAM_REAL_IP_ADDRESS
              value: 127.0.0.1
            - name: UPSTREAM_REAL_IP_HEADER
              value: X-Forwarded-For
            - name: UPSTREAM_REAL_IP_RECURSIVE
              value: "off"
            - name: PROXY_READ_TIMEOUT
              value: "120"
            - name: CLIENT_MAX_BODY_SIZE
              value: 50m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
            - name: logs
              mountPath: /home/frappe/frappe-bench/logs
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
        - name: logs
          persistentVolumeClaim:
            claimName: frappe-logs
